# Namespace erstellen, für das MediaWiki und die Datenbank
apiVersion: v1
kind: Namespace
metadata:
  name: mediawiki

---

# PersistentVolume für MediaWiki-Daten
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-pv
  namespace: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  storageClassName: manual
  hostPath:
    path: /tmp/mediawiki-data

---

# PersistentVolume für SQL-Daten
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-sql-pv
  namespace: mediawiki
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  storageClassName: manual
  hostPath:
    path: /tmp/mediawiki-sql

---

# PersistentVolumeClaim für MediaWiki-Daten
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-pv-claim
  namespace: mediawiki
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---

# PersistentVolumeClaim für SQL-Daten
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki-sql-pv-claim
  namespace: mediawiki
spec:
  resources:
    requests:
      storage: 4Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce

---

# ConfigMap für Umgebungsvariablen
apiVersion: v1
kind: ConfigMap
metadata:
  name: mediawiki-env
  namespace: mediawiki
data:
  MYSQL_DATABASE: wikidatabase
  MYSQL_USER: mediawiki

---

# Secret für Datenbank
apiVersion: v1
kind: Secret
metadata:
  name: mediawiki-mysql-secret
  namespace: mediawiki
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: UGFzc3cwcmQ= #Passw0rd
  MYSQL_USER_PASSWORD: UGFzc3cwcmQ= #Passw0rd

---

# MySQL-Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-mysql
  namespace: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki-mysql
  template:
    metadata:
      labels:
        app: mediawiki-mysql
    spec:
      containers:
        - name: mediawiki-mysql
          image: mysql:8.0
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: mediawiki-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mediawiki-mysql-secret
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: mediawiki-env
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER_PASSWORD
                  name: mediawiki-mysql-secret

---

# MediaWiki-Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-deployment
  namespace: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: mediawiki:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: MEDIAWIKI_DB_HOST
              value: mediawiki-mysql-svc
            - name: MEDIAWIKI_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: mediawiki-env
            - name: MEDIAWIKI_DB_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: mediawiki-env
            - name: MEDIAWIKI_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER_PASSWORD
                  name: mediawiki-mysql-secret

---

# MySQL-Service
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-mysql-svc
  namespace: mediawiki
spec:
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306
  selector:
    app: mediawiki-mysql
  type: ClusterIP

---

# MediaWiki-Service
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-svc
  namespace: mediawiki
spec:
  type: NodePort
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
  selector:
    app: mediawiki

---

# Netzwerkpolicy für eingeschränkten Datenverkehr zwischen MediaWiki und MySQL
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mediawiki-mysql
  namespace: mediawiki
spec:
  podSelector:
    matchLabels:
      app: mediawiki
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: mediawiki-mysql
      ports:
        - protocol: TCP
          port: 3306