apiVersion: v1
kind: Namespace
metadata:
  name: jira

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/jira

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pvc
  namespace: jira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-db-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/jira-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-db-pvc
  namespace: jira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jira-config
  namespace: jira
data:
  JIRA_HOME: /var/atlassian/application-data/jira
  POSTGRES_DB: jira
  POSTGRES_USER: jira

---
apiVersion: v1
kind: Secret
metadata:
  name: jira-secret
  namespace: jira
type: Opaque
data:
  db-password: UGFzc3cwcmQ= #Passw0rd

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-deployment
  namespace: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
        - name: jira
          image: atlassian/jira-software:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          ports:
            - containerPort: 8080
          env:
            - name: JIRA_HOME
              valueFrom:
                configMapKeyRef:
                  name: jira-config
                  key: JIRA_HOME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jira-secret
                  key: db-password
          volumeMounts:
            - mountPath: /var/atlassian/application-data/jira
              name: jira-volume
      volumes:
        - name: jira-volume
          persistentVolumeClaim:
            claimName: jira-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-db-deployment
  namespace: jira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jira-db
  template:
    metadata:
      labels:
        app: jira-db
    spec:
      containers:
        - name: jira-db
          image: postgres:latest
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: jira-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: jira-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jira-secret
                  key: db-password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: jira-db-volume
      volumes:
        - name: jira-db-volume
          persistentVolumeClaim:
            claimName: jira-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: jira-svc
  namespace: jira
spec:
  type: NodePort
  selector:
    app: jira
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: jira-db-svc
  namespace: jira
spec:
  selector:
    app: jira-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-jira-db
  namespace: jira
spec:
  podSelector:
    matchLabels:
      app: jira
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: jira-db
      ports:
        - protocol: TCP
          port: 5432